INSERT INTO application_forms (
  id,
  kind,
  slug,
  title,
  description,
  formbricks_survey_id,
  formbricks_public_url,
  email_question_id,
  linkedin_question_id,
  is_active,
  opens_at,
  closes_at,
  editable_until,
  archive_after,
  display_order
) VALUES
(
  'vol-registration',
  'volunteer',
  'registration',
  'Registration',
  'Ensures the on-site re-registration process runs smoothly on event day. After registration is complete, helps prepare and distribute swag kits to all attendees.',
  'ct3m6uwe4bma93beo57ksz7y',
  'https://forms.awscommunity.id/s/ct3m6uwe4bma93beo57ksz7y',
  'nwcckk7r52a58hfds1ch5uqz',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  10
),
(
  'vol-foh',
  'volunteer',
  'foh',
  'FOH (Front of House)',
  'Responsible for managing multimedia aspects during the event, including presentation systems, live streaming, broadcasting tools, and smooth execution.',
  'ozbz42e9azxrd8d7mj4dm7mi',
  'https://forms.awscommunity.id/s/ozbz42e9azxrd8d7mj4dm7mi',
  'nwcckk7r52a58hfds1ch5uqz',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  20
),
(
  'vol-logistics',
  'volunteer',
  'logistics',
  'Logistics',
  'Manages meals, refreshments, merchandise inventory, stationery supplies, and venue organization.',
  'e80a63c8zwv08t9jzj6hilvy',
  'https://forms.awscommunity.id/s/e80a63c8zwv08t9jzj6hilvy',
  'nwcckk7r52a58hfds1ch5uqz',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  30
),
(
  'vol-design',
  'volunteer',
  'design',
  'Design',
  'Collaborates on visual assets using Figma and creates materials for AWS UG Jakarta brand touchpoints.',
  'e4rwdefi1524fp5ijhv55fbt',
  'https://forms.awscommunity.id/s/e4rwdefi1524fp5ijhv55fbt',
  'nwcckk7r52a58hfds1ch5uqz',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  40
),
(
  'vol-documentation',
  'volunteer',
  'documentation',
  'Documentation',
  'Captures event moments through photography and videography for community memories and visual content.',
  'xu6hmvn9bhd8lua8ni7m57az',
  'https://forms.awscommunity.id/s/xu6hmvn9bhd8lua8ni7m57az',
  'nwcckk7r52a58hfds1ch5uqz',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  50
),
(
  'vol-event',
  'volunteer',
  'event',
  'Event',
  'Owns the event concept and ensures the rundown runs as planned from opening to closing.',
  'n57d614uam0fq8phctem6p57',
  'https://forms.awscommunity.id/s/n57d614uam0fq8phctem6p57',
  'nwcckk7r52a58hfds1ch5uqz',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  60
),
(
  'vol-runner',
  'volunteer',
  'runner',
  'Runner',
  'Supports audience Q&A microphone flow and helps speakers receive stage equipment on time.',
  'ddt09sgt7frtayn96em4ayaw',
  'https://forms.awscommunity.id/s/ddt09sgt7frtayn96em4ayaw',
  'nwcckk7r52a58hfds1ch5uqz',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  70
),
(
  'vol-social-media',
  'volunteer',
  'social-media',
  'Social Media',
  'Live-posts event updates and highlights to AWS UG Jakarta social channels.',
  'irqppigjrez6xwr01m4mgfye',
  'https://forms.awscommunity.id/s/irqppigjrez6xwr01m4mgfye',
  'nwcckk7r52a58hfds1ch5uqz',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  80
),
(
  'vol-liaison-officer',
  'volunteer',
  'liaison-officer',
  'Liaison Officer',
  'Supports speakers before, during, and after events by coordinating schedules and presenter needs.',
  'n3pgifbsaf33mg9f66othb5e',
  'https://forms.awscommunity.id/s/n3pgifbsaf33mg9f66othb5e',
  'nwcckk7r52a58hfds1ch5uqz',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  90
),
(
  'vol-sponsorship',
  'volunteer',
  'sponsorship',
  'Sponsorship',
  'Builds relationships with sponsors and partners to secure event funding, resources, and in-kind support.',
  'a8s0p2ghu1pwhvxse6q6a7p0',
  'https://forms.awscommunity.id/s/a8s0p2ghu1pwhvxse6q6a7p0',
  'nwcckk7r52a58hfds1ch5uqz',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  100
),
(
  'vol-moderator-mc',
  'volunteer',
  'moderator-mc',
  'Moderator / MC',
  'Guides the event flow, keeps energy high, and hosts audience engagement or ice-breaking sessions.',
  'bn48ysfcnfvvo3fgz893rd7g',
  'https://forms.awscommunity.id/s/bn48ysfcnfvvo3fgz893rd7g',
  'nwcckk7r52a58hfds1ch5uqz',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  110
),
(
  'vol-website',
  'volunteer',
  'website',
  'Website',
  'Builds and maintains the AWS UG Jakarta website, keeping event information and community resources up to date.',
  'qs45aymk52hl4ge9pbby14p6',
  'https://forms.awscommunity.id/s/qs45aymk52hl4ge9pbby14p6',
  'nwcckk7r52a58hfds1ch5uqz',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  120
),
(
  'speaker-main',
  'speaker',
  'speaker',
  'Speaker Application',
  'Apply once as a speaker. Choose your preferred talk format inside the application form.',
  'j77s2dhe6hd749brjfhbfxdq',
  'https://forms.awscommunity.id/s/j77s2dhe6hd749brjfhbfxdq',
  'g5lahqsqzv35v5o303da7zox',
  't0bjjqe1mvmjpf14qgxgleo2',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  10
)
ON CONFLICT(kind, slug) DO UPDATE SET
  title = excluded.title,
  description = excluded.description,
  formbricks_survey_id = excluded.formbricks_survey_id,
  formbricks_public_url = excluded.formbricks_public_url,
  email_question_id = excluded.email_question_id,
  linkedin_question_id = excluded.linkedin_question_id,
  is_active = excluded.is_active,
  opens_at = excluded.opens_at,
  closes_at = excluded.closes_at,
  editable_until = excluded.editable_until,
  archive_after = excluded.archive_after,
  display_order = excluded.display_order,
  updated_at = datetime('now');
