INSERT INTO application_forms (
  id,
  kind,
  slug,
  title,
  description,
  formbricks_survey_id,
  formbricks_public_url,
  email_question_id,
  linkedin_question_id,
  is_active,
  opens_at,
  closes_at,
  editable_until,
  archive_after,
  display_order
) VALUES
(
  'vol-registration',
  'volunteer',
  'registration',
  'Registration',
  'Ensures the on-site re-registration process runs smoothly on event day. After registration is complete, helps prepare and distribute swag kits to all attendees.',
  'kb4bat7ovgkotbhuued4eu52',
  'https://forms.awscommunity.id/s/kb4bat7ovgkotbhuued4eu52',
  'ys5lpj6yp3sq5liazl02nksj',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  10
),
(
  'vol-foh',
  'volunteer',
  'foh',
  'FOH (Front of House)',
  'Responsible for managing multimedia aspects during the event, including presentation systems, live streaming, broadcasting tools, and smooth execution.',
  'mvkzikp79ogwcs9uorvz25vk',
  'https://forms.awscommunity.id/s/mvkzikp79ogwcs9uorvz25vk',
  'yxswtrqc5p92bxojcj3zdyak',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  20
),
(
  'vol-logistics',
  'volunteer',
  'logistics',
  'Logistics',
  'Manages meals, refreshments, merchandise inventory, stationery supplies, and venue organization.',
  'g5fvf9lkv4a2lkfdwsj4uz6v',
  'https://forms.awscommunity.id/s/g5fvf9lkv4a2lkfdwsj4uz6v',
  'yxswtrqc5p92bxojcj3zdyak',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  30
),
(
  'vol-design',
  'volunteer',
  'design',
  'Design',
  'Collaborates on visual assets using Figma and creates materials for AWS UG Jakarta brand touchpoints.',
  'c9qdfn702hwtcsd4v71wf95j',
  'https://forms.awscommunity.id/s/c9qdfn702hwtcsd4v71wf95j',
  'ys5lpj6yp3sq5liazl02nksj',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  40
),
(
  'vol-documentation',
  'volunteer',
  'documentation',
  'Documentation',
  'Captures event moments through photography and videography for community memories and visual content.',
  'cmo5tja3s0002p901ew0f2sel',
  'https://forms.awscommunity.id/s/cmo5tja3s0002p901ew0f2sel',
  'yxswtrqc5p92bxojcj3zdyak',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  50
),
(
  'vol-event',
  'volunteer',
  'event',
  'Event',
  'Owns the event concept and ensures the rundown runs as planned from opening to closing.',
  'c9ohze5tqjao2zrphtcw8p1n',
  'https://forms.awscommunity.id/s/c9ohze5tqjao2zrphtcw8p1n',
  'ys5lpj6yp3sq5liazl02nksj',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  60
),
(
  'vol-runner',
  'volunteer',
  'runner',
  'Runner',
  'Supports audience Q&A microphone flow and helps speakers receive stage equipment on time.',
  'rwq2klr69wyif8ecjn5ana9a',
  'https://forms.awscommunity.id/s/rwq2klr69wyif8ecjn5ana9a',
  'ys5lpj6yp3sq5liazl02nksj',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  70
),
(
  'vol-social-media',
  'volunteer',
  'social-media',
  'Social Media',
  'Live-posts event updates and highlights to AWS UG Jakarta social channels.',
  't17lswf5la709a8z1aiyrevy',
  'https://forms.awscommunity.id/s/t17lswf5la709a8z1aiyrevy',
  'ys5lpj6yp3sq5liazl02nksj',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  80
),
(
  'vol-liaison-officer',
  'volunteer',
  'liaison-officer',
  'Liaison Officer',
  'Supports speakers before, during, and after events by coordinating schedules and presenter needs.',
  'z37cp71kvguverugvrx9c90t',
  'https://forms.awscommunity.id/s/z37cp71kvguverugvrx9c90t',
  'ys5lpj6yp3sq5liazl02nksj',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  90
),
(
  'vol-sponsorship',
  'volunteer',
  'sponsorship',
  'Sponsorship',
  'Builds relationships with sponsors and partners to secure event funding, resources, and in-kind support.',
  'fjm0pjoal0712iu1rjizddt6',
  'https://forms.awscommunity.id/s/fjm0pjoal0712iu1rjizddt6',
  'ys5lpj6yp3sq5liazl02nksj',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  100
),
(
  'vol-moderator-mc',
  'volunteer',
  'moderator-mc',
  'Moderator / MC',
  'Guides the event flow, keeps energy high, and hosts audience engagement or ice-breaking sessions.',
  'fn08rrabzik4nzihgkbjxae8',
  'https://forms.awscommunity.id/s/fn08rrabzik4nzihgkbjxae8',
  'ys5lpj6yp3sq5liazl02nksj',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  110
),
(
  'vol-website',
  'volunteer',
  'website',
  'Website',
  'Builds and maintains the AWS UG Jakarta website, keeping event information and community resources up to date.',
  'qbfq8f4ezzqfpzookbzgwi40',
  'https://forms.awscommunity.id/s/qbfq8f4ezzqfpzookbzgwi40',
  'ys5lpj6yp3sq5liazl02nksj',
  'x56v76hx636q7d2e5u989644',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  120
),
(
  'speaker-main',
  'speaker',
  'speaker',
  'Speaker Application',
  'Apply once as a speaker. Choose your preferred talk format inside the application form.',
  'j77s2dhe6hd749brjfhbfxdq',
  'https://forms.awscommunity.id/s/j77s2dhe6hd749brjfhbfxdq',
  'g5lahqsqzv35v5o303da7zox',
  't0bjjqe1mvmjpf14qgxgleo2',
  1,
  NULL,
  NULL,
  NULL,
  datetime('now', '+6 months'),
  10
)
ON CONFLICT(kind, slug) DO UPDATE SET
  title = excluded.title,
  description = excluded.description,
  formbricks_survey_id = excluded.formbricks_survey_id,
  formbricks_public_url = excluded.formbricks_public_url,
  email_question_id = excluded.email_question_id,
  linkedin_question_id = excluded.linkedin_question_id,
  is_active = excluded.is_active,
  opens_at = excluded.opens_at,
  closes_at = excluded.closes_at,
  editable_until = excluded.editable_until,
  archive_after = excluded.archive_after,
  display_order = excluded.display_order,
  updated_at = datetime('now');
